---
title: "Spinners"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{spinners}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(shinybusy)
```


Available spinners are listed below. You can use spinners with following functions : 

- `add_busy_spinner()`
- `use_busy_spinner()`
- `show_modal_spinner()`


## Epic spinners

```{r}
spin_epic("flower")
```

```{r}
spin_epic("pixel")
```

```{r}
spin_epic("hollow-dots")
```

```{r}
spin_epic("intersecting-circles")
```

```{r}
spin_epic("orbit")
```

```{r}
spin_epic("radar")
```

```{r}
spin_epic("scaling-squares")
```

```{r}
spin_epic("half-circle")
```

```{r}
spin_epic("trinity-rings")
```

```{r}
spin_epic("fulfilling-square")
```

```{r}
spin_epic("circles-to-rhombuses")
```

```{r}
spin_epic("semipolar")
```

```{r}
spin_epic("self-building-square")
```

```{r}
spin_epic("swapping-squares")
```

```{r}
spin_epic("fulfilling-bouncing-circle")
```

```{r}
spin_epic("fingerprint")
```

```{r}
spin_epic("spring")
```

```{r}
spin_epic("atom")
```

```{r}
spin_epic("looping-rhombuses")
```

```{r}
spin_epic("breeding-rhombus")
```



## Spin kit

```{r}
style <- "position: relative; height: 50px; width: 50px;"
spin_kit("double-bounce", style = style)
```

```{r}
spin_kit("circle", style = style)
```

```{r}
spin_kit("bounce", style = style)
```

```{r}
spin_kit("folding-cube", style = style)
```

```{r}
spin_kit("rotating-plane", style = style)
```

```{r}
spin_kit("cube-grid", style = style)
```

```{r}
spin_kit("fading-circle", style = style)
```

```{r}
spin_kit("dots", style = style)
```

```{r}
spin_kit("cube", style = style)
```




